GET http://localhost:3001/facilities


### add facility
POST http://localhost:3001/facility/new
Content-Type: application/json

{
    "locationid": "fake-location-id",
    "company": "Testing Dummy Company",
    "address": "1234 Address St.",
    "city": "2307 Morgan St",
    "state": "TX",
    "zip": 75062,
    "phone": "224-374-6283",
    "devices": [
        {
            "hazid": 999999,
            "hazardcat": "Irrigation",
            "testdue": "2025-04-15T00:00:00.000Z",
            "lasttest": "2024-03-12T00:00:00.000Z",
            "manufacturer": "FEBCO",
            "_model": "850",
            "size": "2",
            "serialNumber": "1test1",
            "locationDescription": "Bldg#1 OUTSIDE machine shop",
            
        },
        {
            "hazid": 888888,
            "hazardcat": "Irrigation",
            "testdue": "2025-04-15T00:00:00.000Z",
            "lasttest": "2024-03-12T00:00:00.000Z",
            "manufacturer": "WATTS",
            "_model": "LF007M2QT",
            "size": "1.5",
            "serialNumber": "2test2",
            "locationDescription": "Building 1/ SE corner inside"
        },
        {
            "hazid": 9384,
            "hazardcat": "Main Line",
            "testdue": "2025-04-15T00:00:00.000Z",
            "lasttest": "2024-03-12T00:00:00.000Z",
            "manufacturer": "WATTS",
            "_model": "709",
            "size": "4",
            "serialNumber": "169359",
            "locationDescription": "Bldg 2 West Wall @ Column #23"
        }
    ],
    "testdue": "2025-04-15T00:00:00.000Z"
}
### find facility
GET  http://localhost:3001/facility/67080a6b4e4c255c028c729a

###
### query through facilities
GET  http://localhost:3001/facility/search?query=poly

###
### delete facility
DELETE  http://localhost:3001/facility/delete/67080d6d4e4c255c028cb01c

###
###

### add imported facility
POST http://localhost:3001/facility/newImport
Content-Type: application/json

{  
    "name": "test",
    "testdue": "12/15/2025"
 
   
}
###

### delete ALLLLLLLLLL facility
# DELETE  http://localhost:3001/facility/delete

###

### update facility
PUT http://localhost:3001/facility/update/66c4e209d0200d27fff68fd1/66e3206f04e97c334f4a5eb5
Content-Type: application/json

{  
     "manufacturer": "Febco",
    "model": "850",
    "size": "1",
    "type": "Double Check",
    "serialNumber": "longserial#######",
    "locationDescription": "next to wm",
    "location": {
     "type":"Point"
    ,
    "coordinates":[22.2,34.2]
    }
   
}

###
### add new device
POST http://localhost:3001/device/new
Content-Type: application/json

{  
     "manufacturer": "Febco",
    "model": "850",
    "size": "1",
    "type": "Double Check",
    "serialNumber": "longserial#######",
    "locationDescription": "next to wm",
    "location": {
     "type":"Point"
    ,
    "coordinates":[22.2,34.2]
    }
   
}

### find device
GET  http://localhost:3001/device/67080a6b4e4c255c028c729a/6708071207b07663c923e2ff

###

### delete device
DELETE  http://localhost:3001/device/delete/66e3204097c2a2d8bbb2298b

###

### find and update device
GET  http://localhost:3001/device/addCoords/67080a6b4e4c255c028c729a/6708071007b07663c922eb44/2/1

###